### ISSUE TITLE
(bug) 调用api后，报错未找到sessions表

### ISSUE THREAD

**Issue by Wzixiao** [dyzsasd/SmartHtml#1]
## Description
在首次启动项目时，默认使用sqlite，但是初始化链路中没有创建表的函数被调用

## Error message
sqlite3.OperationalError: no such table: sessions

## Solutions
在```smart_html/core/db/sqlite.py```中SQLiteClient类的__init__中调用同脚本文件的init_db的函数是不错的主意？

**Comment by dyzsasd** [comment]
init_db最好是能够显式调用，主要是为了防止重复init操作过程中可能出现的bug。这里只是本地测试DB，所以不要紧，我们可以把它放到init_app函数里面，最好不要放到client的初始化函数中，这样会给client class增加不必要的流程。
